version: '3'

services:
  motion:
    build: 
      context: "."
      dockerfile: "motion.Dockerfile"
      args:
        - SG_API_KEY=${SG_API_KEY}
        - FROM_EMAIL=${FROM_EMAIL}
        - TO_EMAIL=${TO_EMAIL}
        - IR_CAM_USER=${IR_CAM_USER}
        - IR_CAM_PASS=${IR_CAM_PASS}
        - IR_CAM_URL=${IR_CAM_URL}
        - MOTION_CONF_FILE=motion-full.conf
    volumes: 
      - motion-capture:/capture
    ports:
      - 8080:8080
      - 8081:8081
    devices:
      - ${MOTION_DEVICE}
  motion-light:
    build: 
      context: "."
      dockerfile: "motion.Dockerfile"
      args:
        - MOTION_CONF_FILE=motion-light.conf
        - IR_CAM_USER=${IR_CAM_USER}
        - IR_CAM_PASS=${IR_CAM_PASS}
        - IR_CAM_URL=${IR_CAM_URL}
    ports:
      - 8081:8081
    devices:
      - ${MOTION_DEVICE}
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    volumes:
      - nginx-config:/etc/nginx/conf.d/default.conf
      - nginx-certs:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    links:
     - motion

volumes:
  motion-capture: {}
  nginx-config: {}
  nginx-certs: {}
