version: '3'

services:
  motion:
    build: 
      context: "."
      dockerfile: "motion.Dockerfile"
      args:
        - SG_API_KEY=${SG_API_KEY}
        - FROM_EMAIL=${FROM_EMAIL}
        - TO_EMAIL=${TO_EMAIL}
        - IR_CAM_USER=${IR_CAM_USER}
        - IR_CAM_PASS=${IR_CAM_PASS}
        - IR_CAM_URL=${IR_CAM_URL}
        - MOTION_CONF_FILE=motion-full.conf
        - MOTION_PRIVKEY=${MOTION_FULL_PRIVKEY}
        - SERVER_URL=${SERVER_URL}
        - SERVER_PUBKEY=${SERVER_PUBKEY}
        - MOTION_WG_IP=10.0.0.2
    volumes: 
      - motion-capture:/capture
    ports:
      - 8080:8080
      - 8081:8081
    devices:
      - ${MOTION_DEVICE}
    cap_add:
      - NET_ADMIN
  motion-light:
    build: 
      context: "."
      dockerfile: "motion.Dockerfile"
      args:
        - MOTION_CONF_FILE=motion-light.conf
        - IR_CAM_USER=${IR_CAM_USER}
        - IR_CAM_PASS=${IR_CAM_PASS}
        - IR_CAM_URL=${IR_CAM_URL}
        - MOTION_PRIVKEY=${MOTION_LIGHT_PRIVKEY}
        - SERVER_URL=${SERVER_URL}
        - SERVER_PUBKEY=${SERVER_PUBKEY}
        - MOTION_WG_IP=10.0.0.3
    ports:
      - 8081:8081
    devices:
      - ${MOTION_DEVICE}
    cap_add:
      - NET_ADMIN
  nginx:
    build: 
      context: "."
      dockerfile: "nginx.Dockerfile"
      args:
        - SERVER_PRIVKEY=$SERVER_PRIVKEY
        - MOTION_FULL_PUBKEY=$MOTION_FULL_PUBKEY
        - MOTION_LIGHT_PUBKEY=$MOTION_LIGHT_PUBKEY
    container_name: nginx
    ports:
      - 127.0.0.1:5000:80
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  motion-capture: {}
  nginx-config: {}
  nginx-certs: {}
