version: '3'

services:
  motion:
    build: 
      context: "."
      dockerfile: "motion.Dockerfile"
      args:
        - SG_API_KEY=${SG_API_KEY}
        - FROM_EMAIL=${FROM_EMAIL}
        - TO_EMAIL=${TO_EMAIL}
    volumes: 
      - motion-config:/etc/motion/
    devices:
      - "/dev/video0:/dev/video0"
    

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    volumes:
      - nginx-config:/etc/nginx/conf.d/default.conf
      - nginx-certs:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    links:
     - motion

volumes:
  motion-config:
    external: true
  nginx-config:
    external: true
  nginx-certs:
    external: true
