version: '3'

services:
  motion:
    build: 
      context: "."
      dockerfile: "motion.Dockerfile"
      args:
        - SG_API_KEY=${SG_API_KEY}
        - FROM_EMAIL=${FROM_EMAIL}
        - TO_EMAIL=${TO_EMAIL}
    volumes: 
      - motion-config:/etc/motion/
    ports:
      - 80:8080
    devices:
      - ${MOTION_DEVICE}:"/dev/video0"
  mjpg-streamer:
    build: 
      context: "."
      dockerfile: "mjpg-streamer.Dockerfile"
      args:
        - MJPG_STREAMER_INPUT_PLUGIN=${MJPG_STREAMER_INPUT_PLUGIN}
        - MJPG_STREAMER_USER=${MJPG_STREAMER_USER}
        - MJPG_STREAMER_PASS=${MJPG_STREAMER_PASS}
    platform: linux/arm/v7
    ports:
      - ${MJPG_STREAMER_IP}:80:8080
    devices:
      - ${MJPG_STREAMER_DEVICE}:"/dev/video0"
      - /dev/vchiq:/dev/vchiq
    

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    volumes:
      - nginx-config:/etc/nginx/conf.d/default.conf
      - nginx-certs:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    links:
     - motion

volumes:
  motion-config:
    external: true
  nginx-config:
    external: true
  nginx-certs:
    external: true
